import { NextRequest, NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/admin";

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const warehouseName = searchParams.get("warehouse") || "PaperClip Warehouse";
  const itemId = searchParams.get("itemId");

  let warehouseAddress = "";
  let trackingNumber = "";
  let itemName = "";

  if (itemId) {
    const admin = createAdminClient();
    const { data: item } = await admin
      .from("items")
      .select("*, warehouses(*)")
      .eq("id", itemId)
      .single();

    if (item) {
      itemName = item.name;
      trackingNumber = item.intake_tracking_number || "";
      if (item.warehouses) {
        warehouseAddress = [
          item.warehouses.name,
          item.warehouses.address,
          `${item.warehouses.city}, ${item.warehouses.state} ${item.warehouses.zip}`,
          item.warehouses.country,
        ].join("\n");
      }
    }
  }

  if (!warehouseAddress) {
    warehouseAddress = `${warehouseName}\nPaperClip Fulfillment Center`;
  }

  if (!trackingNumber) {
    trackingNumber = `PC${Date.now().toString().slice(-12)}${Math.floor(Math.random() * 10000).toString().padStart(4, "0")}`;
  }

  const barcodeLines = trackingNumber
    .split("")
    .map((ch) => {
      const code = ch.charCodeAt(0);
      return code % 2 === 0 ? "██ " : "█ ";
    })
    .join("");

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Shipping Label - ${trackingNumber}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Courier New', monospace; background: #f5f5f5; display: flex; justify-content: center; padding: 40px 20px; }
    .label { background: white; width: 4in; padding: 24px; border: 3px solid #000; }
    .header { text-align: center; border-bottom: 2px solid #000; padding-bottom: 12px; margin-bottom: 16px; }
    .header h1 { font-size: 18px; letter-spacing: 2px; }
    .header p { font-size: 10px; color: #666; margin-top: 4px; }
    .section { margin-bottom: 16px; }
    .section-label { font-size: 10px; font-weight: bold; text-transform: uppercase; color: #666; margin-bottom: 4px; }
    .section-content { font-size: 13px; line-height: 1.5; white-space: pre-line; }
    .barcode { text-align: center; padding: 16px 0; border-top: 2px solid #000; border-bottom: 2px solid #000; margin: 16px 0; }
    .barcode .bars { font-size: 28px; line-height: 1; letter-spacing: -2px; }
    .barcode .number { font-size: 11px; margin-top: 8px; letter-spacing: 1px; }
    .footer { text-align: center; font-size: 9px; color: #999; margin-top: 16px; }
    @media print {
      body { background: white; padding: 0; }
      .label { border: none; width: 100%; }
    }
  </style>
</head>
<body>
  <div class="label">
    <div class="header">
      <h1>PAPERCLIP</h1>
      <p>Item Trading Platform</p>
    </div>
    <div class="section">
      <div class="section-label">Ship To</div>
      <div class="section-content">${warehouseAddress.replace(/\n/g, "<br>")}</div>
    </div>
    ${itemName ? `<div class="section"><div class="section-label">Item</div><div class="section-content">${itemName}</div></div>` : ""}
    <div class="barcode">
      <div class="bars">${barcodeLines}</div>
      <div class="number">${trackingNumber}</div>
    </div>
    <div class="footer">
      This label was generated by PaperClip. Print and attach to your package.
    </div>
  </div>
</body>
</html>`;

  return new NextResponse(html, {
    headers: { "Content-Type": "text/html" },
  });
}
